# Generated by Django 2.2.26 on 2022-02-10 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_auto_20220210_1030"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="list",
            name="address",
        ),
        migrations.RemoveField(
            model_name="list",
            name="category",
        ),
        migrations.AddField(
            model_name="list",
            name="vendoraddress",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="list_vendoraddress",
                to="home.List",
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="vendorcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="list_vendorcategory",
                to="home.Mandapform",
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="vendorname",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="list_vendorname",
                to="home.List",
            ),
        ),
    ]
